import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import ShopBanner from '../components/ShopBanner'
import Products from '../components/products'
import Trend from '../components/Trend'
import Sale from '../components/Sale'
import Category from '../components/Category'
import Footer from '../components/Footer'

export default function Home() {
  return(
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ShopBanner />
      <div style={{ marginTop: "50px" }}>
        <Products />
      </div>
      <div style={{ marginTop: "50px" }}>
        <Trend />
      </div>
      <div style={{ marginTop: "80px" }}>
        <Sale />
      </div>
      <div style={{ marginTop: "50px" }}>
        <Category />
      </div>
      <div style={{ marginTop: "50px" }}>
        <Footer />
      </div>
    </div>
  )
}
